version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn mysite.wsgi:application --reload --timeout 1000 --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/usr/src/app/static
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume: