# Generated by Django 4.0.2 on 2022-02-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Company Staff'},
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Normal leave', 'Normal leave'), ('Sick leave', 'Sick leave')], default='Sick leave', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='number_of_leave_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
