# Generated by Django 4.0.2 on 2022-02-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_leave_options_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=250),
        ),
    ]
